# COLORS

colorPrimary = "#43449C"
colorPrimaryDark = "#110547"
colorSecondary = "#A0D7C4"
colorSecondaryOpacity = "rgba(160, 215, 196, 0.4)"
colorGray = "#D4D4D4"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
colorWhite = "#FFFFFF"
colorWhiteOpacity = "rgba(255, 255, 255, 0.5)"
colorBlack = "#000000"
colorRed = "#F15857"

# STYLING ATTRIBUTES

# container used for registration forms
containerFormWidth = "752px"

# container used for main layout
containerContentWidth = "1024px"

borderRadiusButtonSmall = "8px"
borderRadiusCard = "16px"
borderRadiusCardSmall = "8px"
maxWidthBanner = "876px"

image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"

notifyMessagePosition = "top"

# CONTACT DETAILS

# Emails
contactEmail = "kontakt@dopracenakole.cz"

# EXTERNAL URLS

urlAutoMat = "https://auto-mat.cz"
urlFacebook = "https://www.facebook.com/spolekautomat"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlTwitter = "https://twitter.com/spolekautomat"
urlYoutube = "https://www.youtube.com/@spolekautomat"
urlAppStore = "https://apps.apple.com/cz/app/do-pr%C3%A1ce-na-kole/id1564442780"
urlGooglePlay = "https://play.google.com/store/apps/details?id=cz.dopracenakole"
urlVideoLoggingRoutes = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlVideoOnboarding = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"

# CHALLENGE DETAILS

challengeMonth = "may"
challengeStartDate = "2024-08-01T12:00:00"
challengeLoggingWindowDays = 8
defaultDistanceZero = "0.00"

# Challenge registration
entryFeePaymentMin = "390"
entryFeePaymentMax = "2000"
entryFeePaymentOptions = "500,700"

# API CONFIGURATION

apiBase = "https://test.dopracenakole.cz/rest/"
apiVersion = "1.0"

urlApiLogin = "auth/login/"
