# Quiz
# Define Colors

colorPrimary = "#43449C"
colorSecondary = "#A0D7C4"
colorSecondaryOpacity = "rgba(160, 215, 196, 0.4)"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
colorWhite = "#FFFFFF"
colorWhiteOpacity = "rgba(255, 255, 255, 0.5)"
colorBlack = "#000000"
colorRed = "#F15857"

image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"
borderRadiusCard = "16px"
borderRadiusCardSmall = "8px"
maxWidthBanner = "876px"

# Emails
contactEmail = "kontakt@dopracenakole.cz"

# External URLs
urlFacebook = "https://www.facebook.com/spolekautomat"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlTwitter = "https://twitter.com/spolekautomat"
urlYoutube = "https://www.youtube.com/@spolekautomat"
urlAppStore = "https://apps.apple.com/cz/app/do-pr%C3%A1ce-na-kole/id1564442780"
urlGooglePlay = "https://play.google.com/store/apps/details?id=cz.dopracenakole"
urlVideoLoggingRoutes = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlVideoOnboarding = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"

challengeMonth = "may"
challengeStartDate = "2024-10-01T12:00:00"
containerWidth = "752px"
