# COLORS

colorPrimary = "#43449C"
colorPrimaryDark = "#110547"
colorPrimaryOpacity = 0.1
colorSecondary = "#A0D7C4"
colorGray = "#D4D4D4"
colorGrayLight = "#F3F7FF"
colorGrayMiddle = "#DCE1ED"
colorWhite = "#FFFFFF"
colorBlack = "#000000"
colorRed = "#F15857"
colorSecondaryBackgroundOpacity = 0.4
colorWhiteBackgroundOpacity = 0.2

# STYLING ATTRIBUTES

# container used for registration forms
containerFormWidth = "752px"

# container used for main layout
containerContentWidth = "1024px"

borderRadiusButtonSmall = "8px"
borderRadiusCard = "16px"
borderRadiusCardSmall = "8px"
maxWidthBanner = "876px"

image = "image.png"
width = "850px"
title = "Title"
subtitle = "Subtitle"

notifyMessagePosition = "top"

# CONTACT DETAILS

# Emails
contactEmail = "kontakt@dopracenakole.cz"

# LOCAL URLS

urlRTWBBLogo = "#/"
urlLoginRegisterBackgroundImage = "/image/login-register-layout.webp"
urlBaseBackend = "https://test.dopracenakole.cz/"

# EXTERNAL URLS

urlAppStore = "https://apps.apple.com/cz/app/do-pr%C3%A1ce-na-kole/id1564442780"
urlAutoMat = "https://auto-mat.cz"
urlBlog = "https://dopracenakole.cz/novinky-do-prace-na-kole"
urlProjectSourceCode = "https://github.com/auto-mat/ride-to-work-by-bike-frontend"
urlFacebook = "https://www.facebook.com/spolekautomat"
urlFreeSoftwareDefinition = "https://www.gnu.org/philosophy/free-sw.en.html"
urlGooglePlay = "https://play.google.com/store/apps/details?id=cz.dopracenakole"
urlInstagram = "https://www.instagram.com/spolekautomat"
urlAppDataPrivacyPolicy = "https://auto-mat.cz/zasady"
urlTwitter = "https://twitter.com/spolekautomat"
urlVideoLoggingRoutes = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlVideoOnboarding = "https://www.youtube.com/embed/ItfTtrEutgo?rel=0"
urlYoutube = "https://www.youtube.com/@spolekautomat"

# CHALLENGE DETAILS

challengeMonth = "may"
challengeStartDate = "2024-08-01T12:00:00"
challengeLoggingWindowDays = 8
defaultDistanceZero = "0.00"

# Challenge registration
entryFeePaymentMin = "390"
entryFeePaymentMax = "2000"
entryFeePaymentOptions = "500,700"

# Merchandise
iDontWantMerchandiseItemCode = "nic"


# API CONFIGURATION

apiBase = "https://test.dopracenakole.cz/rest/"
apiBaseRtwbbFeed = "https://dopracenakole.cz/feed/"

apiVersion = "1.0"
apiDefaultLang = "cs"

urlApiDiscountCoupon = "discount-coupon/"
urlApiHasUserVerifiedEmail = "auth/registration/has-user-verified-email-address/"
urlApiLogin = "auth/login/"
urlApiLoginGoogle = "auth/google/login/"
urlApiOrganizations = "organizations/"
urlApiLoginFacebook = "auth/facebook/login/"
urlApiMerchandise = "merchandise/"
urlApiRefresh = "auth/token/refresh/"
urlApiRegister = "auth/registration/"
urlApiRegisterCoordinator = "challenge/registration/coordinator/"
urlApiResetPassword = "auth/password/reset/"
urlApiSubsidiaries = "subsidiaries/"
urlApiTeams = "teams/"
urlApiChallengeRegistrationUser = "challenge/registration/user/"
urlApiCities = "cities/"
urlApiThisCampaign = "this_campaign/"

checkIsEmailVerifiedInterval = 20 # seconds
checkIsThisCampaignCompetitionPhaseTypeInterval = 20 # seconds

# DATE TIME FORMATS

dateTimeFormatsAllLocales = '''
{
  "numeric": {
    "year": "numeric",
    "month": "numeric",
    "day": "numeric"
  },
  "monthYear": {
    "year": "numeric",
    "month": "long"
  }
}
'''

# SECRETS

secretString = "SECRET"
googleLoginAppId = "SECRET"
facebookLoginAppId = "SECRET"

# LIBRARIES

facebookLoginSdkVersion = "v21.0"
facebookLoginSdkOptions = '''
{
  "scope": "email,public_profile"
}
'''

# MAP SETTINGS

mapProjection = "EPSG:3857"
mapCenterLon = "14.4378"
mapCenterLat = "50.0755"
mapZoom = "14"
mapGeocodingApiUrl = "https://nominatim.openstreetmap.org/reverse"
mapSourceRtwbb = "https://mnk-osm-tiles.dopracenakole.net/{z}/{x}/{y}.png"
mapSourceOsm = "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
